server:
  port: 7572

spring:
  application:
    name: Import-tramite

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/icep}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB