spring:
  application:
    name: Import-tramite

  data:
    mongodb:
      database: icep
      host: localhost
      port: 27017

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              MongoOperations: DEBUG